apiVersion: v1
kind: Template
metadata:
    name: kubernetes-wordpress-mariadb
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: wp-db-service
      labels:
        app: wordpress
    spec:
        selector:
          app: wordpress
          tier: wordpressdb
        ports:
          - name: database 
            port: 3306
            protocol: TCP
            targetPort: 3306
  - apiVersion: v1
    kind: Service
    metadata:
        name: wp-http-service
    spec:
        selector:
            app: wordpress
            tier: frontend
        ports:
          - name: http
            port: 80
            protocol: TCP
            targetPort: 80
          - name: https
            port: 443
            protocol: TCP
            targetPort: 443
        type: LoadBalancer
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: wp-database-pv
      labels:
        type: local
    spec:
      storageClassName: manual
      capacity:
        storage: 10Gi
      accessModes:
        - ReadWriteOnce
      hostPath:
        path: "/var/lib/mysql"
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: wp-database-pvc
      labels:
        app: wordpress
        tier: wordpressdb
    spec:
      storageClassName: manual
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: wp-front-pv
      labels:
        type: local
    spec:
      storageClassName: manual
      capacity:
        storage: 10Gi
      accessModes:
        - ReadWriteOnce
      hostPath:
        path: "/var/www/html"
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: wp-frontend-pvc
      labels:
        app: wordpress
        tier: frontend
    spec:
      storageClassName: manual
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: wp-db
      labels:
        app: wordpress
    spec:
      selector:
        matchLabels:
          app: wordpress
          tier: wordpressdb
      template:
        metadata:
          labels:
            app: wordpress
            tier: wordpressdb
        spec:
          containers:
            - name: database
              image: mariadb:latest
              ports:
              - containerPort: 3306
              env:
              - name: MYSQL_ROOT_PASSWORD
                value: your_root_password
              - name: MYSQL_DATABASE
                value: wordpress
              - name: MYSQL_USER
                value: wordpress
              - name: MYSQL_PASSWORD
                value: your_wordpress_password
              volumeMounts:
                - name: wordpress-db
                  mountPath: /var/lib/mysql         
          volumes:
          - name: wordpress-db
            persistentVolumeClaim:
              claimName: wp-database-pvc
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: wp-engine
      labels:
        app: wordpress
    spec:
      selector:
        matchLabels:
          app: wordpress
          tier: frontend
      template:
        metadata:
          labels:
            app: wordpress
            tier: frontend
        spec:
          containers:
            - name: blog
              image: wordpress:latest
              ports:
              - containerPort: 80
              env:
              - name: WORDPRESS_DB_HOST
                value: wp-db-service
              - name: WORDPRESS_DB_NAME
                value: wordpress
              - name: WORDPRESS_DB_USER
                value: wordpress
              - name: WORDPRESS_DB_PASSWORD
                value: your_wordpress_password 
                volumeMounts:
              - name: wordpress-pv
                mountPath: /var/www/html
          volumes:
            - name: wordpress-pv
              persistentVolumeClaim:
                claimName: wp-frontend-pvc
